version: '3.9'

services:
  bot:
    container_name: ${PROJECT_NAME}-bot
    build:
      dockerfile: Dockerfile.bot
      context: .
    working_dir: "/usr/src/app/${BOT_NAME:-tg_bot}"
    volumes:
      - .:/usr/src/app/${BOT_NAME:-bot}

    command: python bot.py
    restart: always
    depends_on:
      - db
      - redis
      - web
    env_file: .env

  web:
    container_name: ${PROJECT_NAME}-web
    build:
      dockerfile: Dockerfile.web
      context: .
    working_dir: "/usr/src/app/${PROJECT_NAME:-web}"
    volumes:
      - .:/usr/src/app/${PROJECT_NAME:-web}
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - db
      - redis
    env_file: .env

  db:
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    container_name: ${PROJECT_NAME}-db
    env_file: .env
    ports:
      - 5439:5432

  redis:
    container_name: ${PROJECT_NAME}-redis
    image: redis:7.2-rc3-alpine
    restart: always
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    expose:
      - ${REDIS_PORT}
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf


volumes:
  postgres_data:
  redis_data: