[pytest]
DJANGO_SETTINGS_MODULE = todolist_dj_aiogram.settings_test
python_files = tests.py test_*.py *_tests.py
addopts = -vv -x --cov

;-x: останавливает выполнение тестов, как только тест дает сбой, позволяя нам остановить тестовый запуск прямо сейчас, чтобы мы могли вернуться к отладке нашего теста, а не ждать завершения выполнения тестового набора.
;--lf: запускает набор тестов с последнего проваленного теста, что идеально подходит для избежания постоянного запуска тестов, которые, как мы знаем, прошли на момент отладки.
;-vv: показывает более подробную версию ошибочного утверждения.
;--cov: показать % охваченных тестами тестов (зависит от pytest-covплагина).