# Generated by Django 5.2.5 on 2025-10-19 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('name', models.CharField(max_length=50, verbose_name='категория задач')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='TGUser',
            fields=[
                ('id', models.CharField(editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('tg_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('chat_id', models.BigIntegerField(verbose_name='идентификатор чата')),
                ('title', models.CharField(max_length=100, verbose_name='название задачи')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание задачи')),
                ('deadline', models.DateTimeField(verbose_name='время напоминания')),
                ('is_done', models.BooleanField(default=False, verbose_name='статус')),
                ('categories', models.ManyToManyField(blank=True, related_name='task', to='tdlist_api.category', verbose_name='категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tdlist_api.tguser')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
                'ordering': ['deadline'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tdlist_api.tguser'),
        ),
    ]
